### ISSUE TITLE
[Bug]: Server crash

### ISSUE THREAD

**Issue by Zunwolf1896** [Toadstool-Studios/Creeper-Overhaul#107]
### Bug Description

Honestly, not entirely sure, I dont really understand this crash log, but it is mentioning 

"tech.thatgravyboat.creeperoverhaul.common.entity.base.WaterCreeper.method_6007"

a couple times so I am assuming it is this mod.

### How to Reproduce?

1. On the server
2. I think I can assume someone was in a modded boat and a creeper attacked it? (I am not getting any answers on what players where doing)
3. Sudden unexpected server crash. 

### Expected Behavior

Server not to randomly crash

### Version

3.0.1-fabric

### Mod Loader Version

0.90.0+ 1.20.1 

### Mod Loader

Fabric

### Logs or additional context

https://mclo.gs/VkILcUE

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by Zunwolf1896** [comment]
Just happened again when a player logged on, foudn the culprit. 

They were swimming and ran into an ocean creeper that killed them. We suspect it might be somethign to do with their Origin. 

Second crash report: https://mclo.gs/c6bZDJd

**Comment by Zunwolf1896** [comment]
Ended up spam killing the creepers till the player joined again, Think I managed to get it. No crash. 

![image](https://github.com/bonsaistudi0s/Creeper-Overhaul/assets/88537204/4f90d1e4-8acc-4a8c-a5e1-6cbe0ecca30d)

**Comment by Zunwolf1896** [comment]
And it happened, again, the player took damage from a creeper and the server crashed. We have removed the origin, suspecting it is that causing it. 

https://mclo.gs/RK7Mpq3

**Comment by ThatGravyBoat** [comment]
This is an issue with apoli
