### ISSUE TITLE
[Bug]: Configuration Option for Disabling Block Destruction Doesn't Work on Vanilla Creeper Replacement

### ISSUE THREAD

**Issue by josephgilbert** [Toadstool-Studios/Creeper-Overhaul#108]
### Bug Description

Just as the title says, the config option for disabling creeper explosions destroying blocks does not correctly apply to the vanilla creeper replacement.  

### How to Reproduce?

Using the listed versions of the mod loader and mod, type in false for the destroyBlocks config option. Set the option to replace the default creeper to true as well. The replacement creepers will still destroy blocks.

### Expected Behavior

I expected the vanilla replacement creepers to also not destroy blocks.  They are in fact the only ones that still can even when the config is set to false.

### Version

3.0.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
The option only works for our creepers, not the vanilla creeper as to not break compat with other mods, you can use another mod to do that or turn off mob griefing in vanilla.
