### ISSUE TITLE
[Feature Request]: Fabric data/tag parity with Forge

### ISSUE THREAD

**Issue by ghost** [Toadstool-Studios/Creeper-Overhaul#113]
### Is your feature request related to a problem?

I want to write a datapack to fill in some gaps with CO creeper spawns in Enhanced Ecosphere biomes on Fabric. It's possible to do this with the Forge version of the mod, but the Fabric version only has three folders available, none of which are useful for controlling spawns:

- `\c\tags\entity_types`
- `\creeperoverhaul\loot_tables\blocks`
- `\creeperoverhaul\loot_tables\entities`

### Solution(s)

Could you please add some data controls similar to the Forge version?

### Mod Version

3.0.1-fabric

### Mod Loader Version

1.20.1-0.15.3

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Fabric does not have such a system as forge, I suggest using another mod for this.

**Comment by ghost** [comment]
> Fabric does not have such a system as forge, I suggest using another mod for this.

At the time I wrote this, I thought it needed Forge parity, but all you really need for a datapack creator to be able to add biome mod compatibility is biome tags like the ones Enderman Overhaul uses in this data folder:

\data\endermanoverhaul\tags\worldgen\biome
