### ISSUE TITLE
[Bug]: Creepers no longer spawn in the end

### ISSUE THREAD

**Issue by milodakat** [Toadstool-Studios/Creeper-Overhaul#12]
### Bug Description

After latest/second latest update, creepers no longer spawn in the end. The patch notes mentioned fixing them spawning in the nether but not in the end.

### How to Reproduce?

Creepers used to spawn on islands around the end, they no longer do

### Expected Behavior

Hills Creepers spawn on islands around the main end island

### Version

0.3.0

### Mod Loader Version

0.12.12

### Mod Loader

Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
This is intended they are not supposed to spawn in the end.
