### ISSUE TITLE
[Bug]: Dynamic lighting not working with custom creepers

### ISSUE THREAD

**Issue by PolyframeX** [Toadstool-Studios/Creeper-Overhaul#121]
### Bug Description

Dynamic lighting does not work with any modded creepers when exploding.

### How to Reproduce?

1. Download the mod and a dynamic lighting mod
2. Ensure creepers option is enabled
3. Spawn creeper
4. light creeper with flint and steel

### Expected Behavior

Creeper should emit lighting

### Version

3.0.1

### Mod Loader Version

0.15.7

### Mod Loader

Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
I am not explicitly adding support for dynamic lighting
