### ISSUE TITLE
[Bug]: Creepers dont spawn

### ISSUE THREAD

**Issue by Lucas-Carrarini** [Toadstool-Studios/Creeper-Overhaul#123]
### Bug Description

Im playing a while and cant find a overhaul creeper version
Creepers spawns normally, maybe a config option to change the vanilla to the mod variations will be nice!
Same on Enderman Overhaul

### How to Reproduce?

1. Create a world
2. Try to find a overhauled creeper

### Version

3.0.2

### Mod Loader Version

1.20.1 - 47.2.20

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Cant reproduce
