### ISSUE TITLE
[Bug]: Crash with Thermal Foundation/Expansion

### ISSUE THREAD

**Issue by FrozenToothpaste** [Toadstool-Studios/Creeper-Overhaul#127]
### Bug Description

1.20.1
As of April 10 2024, using latest version of this mod and Thermal Foundation/Expansion it will simply crash

### How to Reproduce?

1. Install Forge for 1.20.1 (I am using 47.2.23)
2. Download Creeper Overhaul and Thermal Expansion and Thermal Foundation
3. Try to launch game 
4. Crash

### Expected Behavior

I expect the game to load and not crash and put me back in the launcher

### Version

3.0.2

### Mod Loader Version

47.2.23

### Mod Loader

Forge

### Logs or additional context

[crash-2024-04-10_16.10.55-client.txt](https://github.com/bonsaistudi0s/Creeper-Overhaul/files/14930166/crash-2024-04-10_16.10.55-client.txt)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by FrozenToothpaste** [comment]
Doesnt happen with Enderman Overhaul btw

**Comment by VoxelVixen** [comment]
I'm having the same problem , adding Creeper Overhaul to my pack that has Thermal Expansion crashes the client with a similar crash-report.
This is 1.20.1 with Forge 47.2.0
Ive tested it with making a pack with just those 2 mods (and libraries) resulting in the same behavior. Downgraded to version 3.0.1 still crashed it.

**Comment by ConiferF** [comment]
I was experiencing the same issue but I found a fix. In the config file for Thermal, the file thermal-client.toml needs to be edited. Everything in the Holdays sections needs to be set to false.  Hope this helps.
