### ISSUE TITLE
[Bug]: version="${version}" causes a crash

### ISSUE THREAD

**Issue by Lolothepro** [Toadstool-Studios/Creeper-Overhaul#134]
### Bug Description

version="${version}" causes a crash

### How to Reproduce?

Launch Minecraft with [Creeper-Overhaul](https://github.com/bonsaistudi0s/Creeper-Overhaul) mod and NeoForge 1.21

### Expected Behavior

no crash

### Version

4.0.0/${version}

### Mod Loader Version

21.0.20-beta

### Mod Loader

N/A

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
you downloaded a mispublished version, please redownload
