### ISSUE TITLE
[Bug]: Broken creeper model

### ISSUE THREAD

**Issue by Versus706** [Toadstool-Studios/Creeper-Overhaul#136]
### Bug Description

I did not take a screenshot, but a creeper I encountered in the Deep Dark had a broken model or textures.

### How to Reproduce?

Go to deep dark
Look for creeper

### Version

4.0.1

### Mod Loader Version

0.15.11

### Mod Loader

Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
please make sure your mod version is actually 4.0.1 and you dont have any textures packs that are changing the texture of creeper overhaul
