### ISSUE TITLE
[Bug]: Crash 1.19.2 Forge 43.4.0

### ISSUE THREAD

**Issue by Felsito** [Toadstool-Studios/Creeper-Overhaul#140]
### Bug Description

Crash report:

		creeperoverhaul-2.0.9-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |2.0.9               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 390f2e31-e898-41c0-a172-06d0570fc368
	FML: 43.4
	Forge: net.minecraftforge:43.4.0
	
	Link of log:
https://mclo.gs/vkcRH0U

I was adding mods and all was okay, the problem was when I add the mod resourcefullib-forge-1.19.2-1.1.24 for endermanoverhaul-forge-1.19.2-0.0.2 mod. I though the problem was the resourcefullib but the crash says that is the creeper overhoul

### Version

2.0.9

### Mod Loader Version

43.4.0

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/vkcRH0U

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
this is an issue with travelers backpack
