### ISSUE TITLE
[Bug]: NeoForge 1.21 Crash on startup

### ISSUE THREAD

**Issue by NielsPilgaard** [Toadstool-Studios/Creeper-Overhaul#141]
### Bug Description

When I launch the game it crashes.

### How to Reproduce?

- Install Creeper Overhaul and NeoForge 21.0.43
- Launch the game

### Expected Behavior

For the game to start

### Version

Creeperoverhaul-neoforge-1.21-4.0.1

### Mod Loader Version

1.21.0-21.0.43-beta

### Mod Loader

N/A

### Logs or additional context

https://gist.github.com/NielsPilgaard/85cea4e2ca1a81543befa02b9e7f8262

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
fixed in 4.0.2
