### ISSUE TITLE
[Bug]: Crashma Game 1.21

### ISSUE THREAD

**Issue by makumaku1974** [Toadstool-Studios/Creeper-Overhaul#142]
### Bug Description

Idk how to explain it well because it only said "was cause by creeper overhaul"

### How to Reproduce?

1. I Launched my game with 375 mods

### Expected Behavior

Crash on Launch

### Version

4.0.2

### Mod Loader Version

0.15.11

### Mod Loader

Fabric

### Logs or additional context

https://mclo.gs/gtVZ28n
https://mclo.gs/KOmx8CW

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by mpustovoi** [comment]
Can confirm with my 250 mods, but my instance just says `Caught error loading resourcepacks!`.
I had to look for the reason by a long method of exclusion.

**Comment by mpustovoi** [comment]
I can't reproduce this error on a clean build with only `Creeper Overhaul` and its dependencies.
Probably, this is some kind of incompatibility.

**Comment by makumaku1974** [comment]
now i got like 460 mods i still hope this mod works after updates. Because this is a fun mod.

**Comment by ThatGravyBoat** [comment]
you need to update resourcefullib
