### ISSUE TITLE
[Bug]: Minecraft would not load. 1.21 After installing Creeper Overhaul

### ISSUE THREAD

**Issue by makumaku1974** [Toadstool-Studios/Creeper-Overhaul#143]
### Bug Description

So I did what you said updated both resourcefulconfig and resourcefulib and now I am having a problem of the game not loading. Can you please check my logs if there are any problems?

### Version

4.0.3

### Mod Loader Version

0.15.11

### Mod Loader

Fabric

### Logs or additional context

https://mclo.gs/xob0d1e

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Nothing in there is related to creeper overhaul, there are a lot of errors due to using tlauncher and nothing being able to connect.
