### ISSUE TITLE
No open source, the latest version of gecko is not compatible, 1.18.2[Bug]: 

### ISSUE THREAD

**Issue by zc1108aaa** [Toadstool-Studios/Creeper-Overhaul#144]
### Bug Description

[crash-2024-07-08_23.42.54-client.txt](https://github.com/user-attachments/files/16131654/crash-2024-07-08_23.42.54-client.txt)
1
[latest.log](https://github.com/user-attachments/files/16131663/latest.log)

### Version

1.3.1

### Mod Loader Version

1.18.2-0.15.11

### Mod Loader

Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
That is not a creeper overhaul issue
