### ISSUE TITLE
[Bug]: typo in config name

### ISSUE THREAD

**Issue by VaporeonScripts** [Toadstool-Studios/Creeper-Overhaul#149]
### Bug Description

![image](https://github.com/user-attachments/assets/871caafb-d757-4f96-877e-c446302589e6)

### How to Reproduce?

check config and u will see the typo

### Expected Behavior

typo

### Version

4.0.4

### Mod Loader Version

0.16.2

### Mod Loader

Fabric

### Logs or additional context

![image](https://github.com/user-attachments/assets/2f41c767-e371-4fb5-a16b-3411df13a83e)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
this cant be changed or it will break every existing config so it will stay
