### ISSUE TITLE
[Bug]: crash report

### ISSUE THREAD

**Issue by BrokenDawn627** [Toadstool-Studios/Creeper-Overhaul#15]
### Bug Description

cilent crash

### Version

0.3.0 fabric

### Mod Loader Version

fabric 0.13.2

### Mod Loader

Fabric

### Logs or additional context

[crash-2022-02-16_10.02.59-server.txt](https://github.com/Toadstool-Studios/Creeper-Overhaul/files/8085581/crash-2022-02-16_10.02.59-server.txt)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Report this to crafttweaker as this is an issue with them not us.
