### ISSUE TITLE
[Feature Request]: Restore original creepers instead of merging them with plains creepers

### ISSUE THREAD

**Issue by Loreb29** [Toadstool-Studios/Creeper-Overhaul#152]
### Is your feature request related to a problem?

The mod makes default creepers to be "plains creepers" instead, making creepers incompatible with any resourcepacks that aim to change the creeper texture.

### Solution(s)

Removing the plains creeper, or add it as an actual variation with a different entity, like the other added creepers, but don't modify the default creeper.

### Describe alternatives you've considered

Use CEM to add the plains variant.

### Mod Version

3.0.2

### Mod Loader Version

47.3.0

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
You can disable this in the config
