### ISSUE TITLE
[Bug]: player data coruption

### ISSUE THREAD

**Issue by randomhumon** [Toadstool-Studios/Creeper-Overhaul#153]
### Bug Description

when this mod was added to my minecraft smp it started randomly crashing and deleating player data

### How to Reproduce?

creat a minecraft server on wise hosting
play on it for around a month and a half
instal the mod

### Expected Behavior

repeated crashing which removes all unsaved player data leaving the game will save player data

### Version

1.21

### Mod Loader Version

idk

### Mod Loader

Forge, Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
this mod does 0 things with the data
