### ISSUE TITLE
[Bug]: Crash on startup.

### ISSUE THREAD

**Issue by Torathion** [Toadstool-Studios/Creeper-Overhaul#154]
### Bug Description

I can't start the game with this mod installed for some reason.

### How to Reproduce?

No steps involved, just start the game with the mod installed.

### Expected Behavior

Not to crash.

### Version

4.0.5

### Mod Loader Version

Fabric 0.16.5

### Mod Loader

Fabric

### Logs or additional context

Crash log: https://mclo.gs/JrgGPtG
Latest log: https://mclo.gs/kqj2rNY

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
issue with nameplate mod not creeper overhaul

**Comment by Torathion** [comment]
Yeah... I didn't saw that.
