### ISSUE TITLE
[Feature Request]: Say Resourceful Lib is required when missing

### ISSUE THREAD

**Issue by yrthue** [Toadstool-Studios/Creeper-Overhaul#156]
### Is your feature request related to a problem?

Both on Modrinth and Curseforge dependency on Resourceful Lib is pointed, but on startup with Fabric when its missing game is just crashes without mentioning of Resourceful Lib dependency missing. Crash log is just points to missing Java class of Resourceful Config.

### Solution(s)

Should mention Resource Lib dependency on Fabric incompatibilities screen.

### Mod Version

4.0.5

### Mod Loader Version

0.16.5

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Added
