### ISSUE TITLE
[Bug]: Cave/Dripstone Creepers spawning in Deep Dark biome

### ISSUE THREAD

**Issue by Thiana** [Toadstool-Studios/Creeper-Overhaul#158]
### Bug Description

The Deep Dark is supposed to have no regular mob spawning but with v4.0.4 on MC 1.21 it's spawning a lot of Dripstone and Cave Creepers.

![2024-10-03_15 26 23](https://github.com/user-attachments/assets/84a4b7c2-3a9d-40c2-aa94-61ca4b271942)

### How to Reproduce?

Go to any deep dark biome.

### Expected Behavior

No explosively loud mobs near sculk sensors :)

### Version

4.0.4

### Mod Loader Version

NeoForge 21.1.63

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by wingedseahorse** [comment]
+1

**Comment by ThatGravyBoat** [comment]
Fixed in next version
