### ISSUE TITLE
[Feature Request]: Mushroom creeper requests.

### ISSUE THREAD

**Issue by pantsguyapp** [Toadstool-Studios/Creeper-Overhaul#16]
### Is your feature request related to a problem?

Mushroom creepers are being targeted by Bunfungi from Alex's mobs

### Solution(s)

classified as a "friendly mob" instead of a hostile mob, yet still a creeper.
Remove any aggrovation left on them

### Describe alternatives you've considered

Have them ignitable with a flint n steel, they maybe passive but still can be deadly

### Mod Version

0.3.0

### Mod Loader Version

1.18.1

### Mod Loader

Forge

### Additional context

Maybe have them chargable as well???

**Comment by ThatGravyBoat** [comment]
They are already "passive" they don't have an anger goal and can also still be lit with a flint and steal like you said and are categorized as a creature, not a monster so not much else.
