### ISSUE TITLE
[Bug]: Version 4.0.5 on CF for NeoForge is named for Fabric

### ISSUE THREAD

**Issue by Kanzaji** [Toadstool-Studios/Creeper-Overhaul#160]
### Bug Description

Version 4.0.5 of the mod on CF is named with prefix [Fabric] 😅 Took me a while to realise it's actually for NeoForge.

https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul/files/all?page=1&pageSize=20&version=1.21.1

### How to Reproduce?

1. Go to https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul/files/all?page=1&pageSize=20&version=1.21.1
2. 😄

### Version

4.0.5

### Mod Loader Version

None

### Mod Loader

Forge

### Acknowledgement

- [x] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Fixed
