### ISSUE TITLE
[Bug]: Crash with New Supplementaries

### ISSUE THREAD

**Issue by CraftyZombie** [Toadstool-Studios/Creeper-Overhaul#162]
### Bug Description

The game crashes on startup due to Supplementaries now using the rendering API that CO modifies.
<img width="1122" alt="Screen Shot 2024-11-02 at 1 55 27 PM" src="https://github.com/user-attachments/assets/eaf1421f-2b25-4fa9-9a87-5d8c2171b984">

### How to Reproduce?

1. Start the game.

### Expected Behavior

The game doesn't crash.

### Version

3.0.2

### Mod Loader Version

1.20.1 - 47.3.11

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/CraftyZombie/c57dcb94f43749fc47b5870e788e6c61

Mod list and versions:
<img width="309" alt="Screen Shot 2024-11-02 at 1 02 44 PM" src="https://github.com/user-attachments/assets/085a74dc-fbc9-4208-813b-55b91a3d6212">

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by szunakabeats** [comment]
same issue here.

**Comment by ThatGravyBoat** [comment]
This is an issue with Supplementaries, this event was actually removed in later versions of forge because mods like Supplementaries were using it incorrectly like such.
