### ISSUE TITLE
[Bug]: Minercraft 1.21.1, Fabric 0.16.9

### ISSUE THREAD

**Issue by arkhanan** [Toadstool-Studios/Creeper-Overhaul#164]
### Bug Description

'tech.thatgravyboat.creeperoverhaul.fabric.CreepersClientFabric' sehnd this error 

### How to Reproduce?

The game crash when i try to open minercaft 

### Expected Behavior

Minercraft launcher open 

### Version

1.21 - 4.05

### Mod Loader Version

0.16.9

### Mod Loader

Fabric

### Logs or additional context

[crash-2024-11-18_10.32.25-client.txt](https://github.com/user-attachments/files/17803582/crash-2024-11-18_10.32.25-client.txt)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by FriedrichNietzsche8** [comment]
make sure you installed Resourceful Lib, Resourceful Config and Geckolib

**Comment by ThatGravyBoat** [comment]
This is an issue with knightquest
