### ISSUE TITLE
[Bug]: Creepers do not turn invisibile with the invisibility effect.

### ISSUE THREAD

**Issue by Frozeh** [Toadstool-Studios/Creeper-Overhaul#165]
### Bug Description

When any Creeper-type is given the invisibility effect they do not turn invisible.

### How to Reproduce?

1. Start a new world.
2. Spawn a creeper
3. Splash a Splash Potion of Invisibility on the Creeper
4. Does not turn invisible

### Expected Behavior

Vanilla Creepers turn invisible when given the effect, therefore it is expected that a Creeper turns invisible with the invisibility effect.

### Version

4.0.5

### Mod Loader Version

NeoForge - 1.21.1  21.1.83

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Fixed in next version
