### ISSUE TITLE
[Bug]: Server-based rendering crash

### ISSUE THREAD

**Issue by Sunconure11** [Toadstool-Studios/Creeper-Overhaul#17]
### Bug Description

Something with creeper rendering causes players to get crashed out of servers

### How to Reproduce?

1. Encounter a creeper somewhere
2. Crash

### Expected Behavior

This to not happen

### Version

0.3.0

### Mod Loader Version

1.18.1-0.13.3

### Mod Loader

Fabric

### Logs or additional context

https://github.com/bernie-g/geckolib/issues/232

https://bytebin.lucko.me/HvVfTCYcRa

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
send latest.log crash log is useless

**Comment by Sunconure11** [comment]
Huh... what the shit. It's gone.

**Comment by ThatGravyBoat** [comment]
what?

**Comment by Sunconure11** [comment]
Error stopped. I tried to get a latest log for you, and the error was no longer happening.

**Comment by ThatGravyBoat** [comment]
If the error is what I suspect it is it should only happen if either the glow layer appears or the charged layer appears so if you either get close to a creeper or if a creeper is charged, but I have a lot of doubts about this issue as if it were as easy as going near a creeper I would have probs been reported long ago

**Comment by Sunconure11** [comment]
I managed to approach the creeper that was likely causing the issue, and it wasn't glowing or charged.

**Comment by ThatGravyBoat** [comment]
Minecraft saves previous logs in gzipped files so if you can get one of the previous logs where it did crash that would be great.

**Comment by Sunconure11** [comment]
https://pastebin.com/GThpTSum

**Comment by ThatGravyBoat** [comment]
delete that paste it contains sensitive info
which is weird as normally it removes that info so the game is being launched in a weird way

**Comment by Sunconure11** [comment]
Would have to delete that response then, since the paste is not under any account

**Comment by ThatGravyBoat** [comment]
is it still happening? because that log does not contain the log messages that I added to check if the shader failed and there is none so I'm very confused what is actually happening.
if it continues to happen reopen the issue.

**Comment by Sunconure11** [comment]
It's not happening anymore.
