### ISSUE TITLE
[Bug]: Crepper don't change biome wise

### ISSUE THREAD

**Issue by luckykari** [Toadstool-Studios/Creeper-Overhaul#28]
### Bug Description

Creepers won't change depending on the biome.
I have Fabric and tried loading both resource pack or mod to try if one worked and non did.

![image](https://user-images.githubusercontent.com/108314785/176081046-f2c9eabf-6b44-4cf8-93b9-b9526f9cb3e8.png)

### Version

1.3.1

### Mod Loader Version

18.2

### Mod Loader

Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
The mod adds new spawn eggs for each new creeper and I don't work on the texture pack so you would have to contact them via other means as this is for the mod only.
