### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CNolan75** [Toadstool-Studios/Creeper-Overhaul#31]
### Bug Description

1. entered a snow biome. 2. killed a snow creeper 3. entered a structure from the repurposed structures mod and the game crashed giving the error message that the issue may have been caused by creeper overhaul 2.0.0.

### How to Reproduce?

1. entered a snow biome. 2. killed a snow creeper 3. entered a structure from the repurposed structures mod and the game crashed giving the error message that the issue may have been caused by creeper overhaul 2.0.0.

### Version

1.19

### Mod Loader Version

0.14.8 (current)

### Mod Loader

Fabric

### Logs or additional context

Aa---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 7/11/22, 7:55 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.hitSound" is null
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.CreeperType.getHitSound(CreeperType.java:56)
	at tech.thatgravyboat.creeperoverhaul.common.entity.goals.CreeperMeleeAttackGoal.attack(CreeperMeleeAttackGoal.java:27)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal:144)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.tick(PrioritizedGoal:65)
	at net.minecraft.entity.ai.goal.GoalSelector.tickGoals(GoalSelector:119)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector:110)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:753)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2639)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:553)
	at net.minecraft.entity.mob.HostileEntity.tickMovement(HostileEntity:44)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2384)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:353)
	at net.minecraft.entity.mob.CreeperEntity.tick(CreeperEntity:162)
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.BaseCreeper.tick(BaseCreeper.java:181)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:711)
	at net.minecraft.world.World.tickEntity(World:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:370)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:338)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.CreeperType.getHitSound(CreeperType.java:56)
	at tech.thatgravyboat.creeperoverhaul.common.entity.goals.CreeperMeleeAttackGoal.method_6288(CreeperMeleeAttackGoal.java:27)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:753)
	at net.minecraft.class_1309.method_6007(class_1309.java:2639)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2384)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_1548.method_5773(class_1548.java:162)
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.BaseCreeper.method_5773(BaseCreeper.java:181)
	at net.minecraft.class_3218.method_18762(class_3218.java:711)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)

-- Entity being ticked --
Details:
	Entity Type: creeperoverhaul:snowy_creeper (tech.thatgravyboat.creeperoverhaul.common.entity.base.NeutralCreeper)
	Entity ID: 15838
	Entity Name: Snowy Creeper
	Entity's Exact location: 3254.24, 96.00, -1328.50
	Entity's Block location: World: (3254,96,-1329), Section: (at 6,0,15 in 203,6,-84; chunk contains blocks 3248,-64,-1344 to 3263,319,-1329), Region: (6,-3; contains chunks 192,-96 to 223,-65, blocks 3072,-64,-1536 to 3583,319,-1025)
	Entity's Momentum: 0.02, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,AngerTime:346,AngryAt:[I;120634910,1545159321,-1082690232,1996280383],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.0d,Name:"creeperoverhaul:reach_distance"},{Base:0.0d,Name:"minecraft:generic.armor"},{Base:0.25d,Name:"minecraft:generic.movement_speed"},{Base:8.0d,Name:"minecraft:generic.attack_damage"},{Base:40.0d,Name:"minecraft:generic.max_health"},{Base:16.0d,Modifiers:[{Amount:0.05893323571380226d,Name:"Random spawn bonus",Operation:1,UUID:[I;-545398325,-400210369,-1835798378,1826952063]}],Name:"minecraft:generic.follow_range"}],BalmData:{},Brain:{memories:{}},CanPickUpLoot:0b,DeathTime:0s,ExplosionRadius:3b,FallDistance:0.0f,FallFlying:0b,Fire:-1s,Fuse:30s,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:40.0f,HurtByTimestamp:0,HurtTime:0s,Invulnerable:0b,LeftHanded:0b,Motion:[0.021959449963558062d,-0.0784000015258789d,0.0d],OnGround:1b,PersistenceRequired:0b,PortalCooldown:0,Pos:[3254.2369042855125d,96.0d,-1328.4972542108849d],Rotation:[269.6505f,-15.292545f],Sheared:0b,UUID:[I;1705120600,1143162528,-1262667115,1174051699],ignited:0b,killedbywarden:0b}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['ClamantCube'/14921, l='ServerLevel[New World]', x=3191.69, y=116.00, z=-1266.70]]
	Chunk stats: 5156
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 13352 game time, 13352 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 83466 (now: false), thunder time: 110281 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 12.3.1
	Java Version: 18.0.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 2471384144 bytes (2356 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1 Pro
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1 Pro
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 13309.36
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 731.75
	JVM Flags: 2 total; -Xms512m -Xmx6144m
	Fabric Mods: 
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.28
		auditory: Auditory 0.0.2-1.19
		autoswitch: AutoSwitch 5.1.3-alpha.1
			autoswitch-api: AutoSwitch API 1.1.0
			org_aeonbits_owner_owner: owner 1.0.12
		balm-fabric: Balm 4.3.0+0
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		clickthrough: ClickThrough 1.19-fabric0.53.3-0.4
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		cotw: Curse Of The Warden 1.0.0
		creeperoverhaul: Creeper Overhaul 2.0.0
		cryingghasts-fabric: Crying Ghasts (Fabric) 1.6
		deathknell: DeathKnell 4.0.1
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.5
		durabilityviewer: Giselbaers Durability Viewer 1.19-fabric0.53.3-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		dyeallthethings: Dye All The Things 1.2.1
		earthbounds: Earthbounds 1.19-1.1.3
		earthtojavamobs: Earth2Java 1.9.2
		ecologics: Ecologics 2.1.3
		effective: Effective 1.2.2
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fastload: Fast Load 1.1.5
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		forgotten_features: Forgotten Features 1.5.1+1.19
		fpsdisplay: FPS-Display 1.5.0+1.19
		friendsandfoes: Friends&Foes 1.5.4
			mm: Manningham Mills 2.3
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		horsestatsvanilla: Horse Stats Vanilla 4.2.0
			cloth-config: Cloth Config v6 7.0.72
				cloth-basic-math: cloth-basic-math 0.6.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.8
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		itemborders: Item Borders 1.1.6
		java: OpenJDK 64-Bit Server VM 18
		justmobheads-fabric: Just Mob Heads (Fabric) 5.4
		legendarytooltips: Legendary Tooltips 1.2.6
		lithium: Lithium 0.8.0
		lod: Distant Horizons 1.6.5a
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
		mavm: More Axolotl Variants Mod 1.1.0
		minecraft: Minecraft 1.19
		mobifier: Mobifier 2.0.0.0
		modsettings: ModSettings 1.1.0+1.19
		mooshroomtweaks-fabric: Mooshroom Tweaks (Fabric) 1.8
		mousetweaks: Mouse Tweaks 2.22
		namepain: Name Pain 1.4.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		npcvariety: NPC Variety 2.2.1
		phosphor: Phosphor 0.8.1
		probablychests: Probably Chests 0.4.4
		quartzelv: Quartz Elevator 2.1.3+1.19
		repurposed_structures: Repurposed Structures 6.1.1+1.19
			midnightlib: MidnightLib 0.5.2
		roughlyenoughitems: Roughly Enough Items 9.1.511
		rpgdifficulty: Rpg Difficulty 1.2.0
		seasons: Fabric Seasons 1.4-BETA+1.19
		smoothswapping: Smooth Swapping 0.4.5
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		statuseffecttimer: Status Effect Timer 1.1.1+1.19
		stepup: StepUp 1.19-fabric0.53.3-1.1
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		terrarianslimes: Terrarian Slimes 1.3-BETA+1.19
		villagerdeathmessages-fabric: Villager Death Messages (Fabric) 2.3
		villagernames-fabric: Villager Names (Fabric) 3.6
		waystones: Waystones 11.0.1
		yigd: You're in Grave Danger 1.4.1
	Loaded Shaderpack: ComplementaryReimagined_r1
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['ClamantCube'/14921, l='ServerLevel[New World]', x=3191.69, y=116.00, z=-1266.70]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 2
	Suspected Mods: Minecraft (minecraft), Creeper Overhaul (creeperoverhaul)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
This has been fixed get 2.0.1
