### ISSUE TITLE
[Bug]: the game crashes when a snow creeper hits me.

### ISSUE THREAD

**Issue by Fkncloudy** [Toadstool-Studios/Creeper-Overhaul#32]
### Bug Description

I was testing the mod in creative and I changed the mode to survival to see the creeper attacks.
When I was with the snow creeper, I hit him and when he wanted to hit me the game crashed

### How to Reproduce?

1. Create a new profile with fabric in 1.19 and install the mod
2. Open Minecraft and create a new world in crative mode.
3. Spawn a snow creeper 
4. Put on survival mode and hit the creeper, wait for it to hit you. 

### Expected Behavior

just make sure it doesn't crash when it happens):

### Version

2.0.0

### Mod Loader Version

0.14.8

### Mod Loader

Fabric

### Logs or additional context

Here´s the crash report in crashy:
https://crashy.net/GUDN5HHrdyy6PA1MpFAC

Here's the crash in txt:
https://bytebin.lucko.me/vNsgcVButX

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
This has been fixed get 2.0.1
