### ISSUE TITLE
[Bug]: Possible crash related here on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [Toadstool-Studios/Creeper-Overhaul#34]
### Bug Description

I'm running into an unusual mixin crash, and your mod seems to be one of the ones blamed.

### How to Reproduce?

1. Crash
2. ???
3. https://pastebin.com/B7XEWfx3

https://pastebin.com/fe27jZss

### Expected Behavior

Game to boot up

### Version

2.0.1

### Mod Loader Version

0.17.1-beta 6

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/B7XEWfx3

https://pastebin.com/fe27jZss

I am on Quilt

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
We do not implicitly support quilt

**Comment by Sunconure11** [comment]
I explored this a bit further when trying to kill another bug, and ran into this error:

https://pastebin.com/NCKULuSb

Really strange mixin error. I would advise at least giving it a look, even if you don't support Quilt.

**Comment by AbsolemJackdaw** [comment]
from what I can tell a bunch of fabric classes aren't found. 
this may bewhere quilt and fabric are starting to split up ? that or either one is not up to date

**Comment by AbsolemJackdaw** [comment]
Quilt's reply : 
> We don't support fabric impl classes because you shouldn't be using them anyway

so the quilt loader isn't compatible with some fabric classes.

The solution here is to not use quilt to load these fabric mods

**Comment by ThatGravyBoat** [comment]
I have changed how I did the only thing that used the fabric impl for, this was 1 to let people decide even those I do not officially support quilt and because the way I did it could cause problems if fabric updated their impl now I only use the official API files.

The new version is creeperoverhaul-2.0.2-fabric
