### ISSUE TITLE
[Bug]: Instant Loading Crash - 1.19 Forge v41.0.100

### ISSUE THREAD

**Issue by ladypluu** [Toadstool-Studios/Creeper-Overhaul#36]
### Bug Description

The mod crashes upon loading into Minecraft's main menu. Happened with other mods installed, then isolated the issue to creeperoverhaul and geckolib and it persists.

### How to Reproduce?

1. Install _creeperoverhaul-2.0.1-forge.jar_ and _geckolib-forge-1.19-3.1.9_ into .minecraft/mods (no other mods installed)
2. Launch Minecraft
3. Window pops up with _java.lang.reflect.InvocationTargetException: null_ error

### Expected Behavior

Expected to get to the Minecraft main menu.

### Version

2.0.1-forge

### Mod Loader Version

1.19-forge-41.0.100

### Mod Loader

Forge

### Logs or additional context

[https://pastebin.com/Gqx26NLx](https://pastebin.com/Gqx26NLx)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
As of right now Creeper Overhaul only supports forge 64-93. When forge releases a Recommended build it will be updated
