### ISSUE TITLE
[Bug]: Crashes after summoned a charged creeper

### ISSUE THREAD

**Issue by gousisme** [Toadstool-Studios/Creeper-Overhaul#41]
### Bug Description

Crash log:
[crash-2022-08-07_12.05.10-client.txt](https://github.com/bonsaistudi0s/Creeper-Overhaul/files/9276210/crash-2022-08-07_12.05.10-client.txt)
 

### How to Reproduce?

1. Create a new world
2. Summon a charged creeper
3. Game crashes

### Expected Behavior

Summon a charged creeper without crashing the game

### Version

2.0.2

### Mod Loader Version

1.19.1 - 42.0.9

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
this does not seem to be an issue with creeper overhaul at all, it is likely an issue with another mod.

**Comment by gousisme** [comment]
Only have rubidium and oculus installed, so this mod is incompatible with those two?

**Comment by ThatGravyBoat** [comment]
Well seeing as I dont do anything fancy with rendering besides a simple model and shader then it may be a bug on their part I would say you should report it to them.

**Comment by ThatGravyBoat** [comment]
it seems to be an issue with oculus and its more than just this mod that causes it to happen on their end so it doesn't really seem like I can do much.
