### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BrachoAlex** [Toadstool-Studios/Creeper-Overhaul#42]
### Bug Description

Changed Creepers crash the game. 

### How to Reproduce?

Summon a creeper.
Summon a Lightbolt to charge the Creeper. 

### Expected Behavior

Creeper gets charged.

### Version

2.0.2

### Mod Loader Version

1.19.0 - 41.1.0

### Mod Loader

Forge

### Logs or additional context

Mod version : 2.0.2
Geckolib version: 1.19-3.1.16

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
You seemed to have magically not read the statement that you were asked to read to click the checkbox 😃 
Provide a crash report and I will reopen, please read instead of clicking buttons and not reading what it says 😃
