### ISSUE TITLE
[Bug]: Charged Creepers crash the game from a faulty/non-registered RenderType

### ISSUE THREAD

**Issue by CDAGaming** [Toadstool-Studios/Creeper-Overhaul#43]
### Bug Description

See title.

### How to Reproduce?

1. Load World
2. Spawn any of the Creepers from this mod.
3. Summon a lighting bolt, observe game crash when the creeper becomes charged

### Expected Behavior

Creepers should render charged properly.

### Version

2.0.2-forge

### Mod Loader Version

43.1.3

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/28DV09H

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by CDAGaming** [comment]
Related to #41 that also experienced the same issue and closed without coorespondance.

**Comment by ThatGravyBoat** [comment]
fixed with bfa1afa
