### ISSUE TITLE
[Bug]: Forge Creeper Overhaul does not have correct version.

### ISSUE THREAD

**Issue by MarbleGateKeeper** [Toadstool-Studios/Creeper-Overhaul#47]
### Bug Description

The version is set to 1.0.0 in mods.toml.

### How to Reproduce?

1.see mods.toml

### Version

2.0.4

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
Fixed in version 2.0.5 when curse approves it.
