### ISSUE TITLE
[Feature Request]: Modeling on shroom creeper

### ISSUE THREAD

**Issue by Psychodeus** [Toadstool-Studios/Creeper-Overhaul#48]
### Mod Version

2.0.3

### Mod Loader Version

1.19.2 - 0.14.9

### Mod Loader

Fabric

### Additional context

![image](https://user-images.githubusercontent.com/93028949/194689527-24d1e99c-d623-4c9c-837e-b07437ee918b.png)
![Shroom](https://user-images.githubusercontent.com/93028949/194689774-71ed0c9d-a2fe-4d94-8e1a-5e6e5881e8a2.png)

Please add something like this, cause the default one felt wrong. So please, add 1 more shroom-red-block-model on top of the default one. I photoshop it to visualize what I meant.

**Comment by ThatGravyBoat** [comment]
Suggest this in the discord to josh as I am not the artist. https://discord.gg/sGwxnFV
