### ISSUE TITLE
[Bug]: Only badlands creepers spawning in Mushroom Fields biome

### ISSUE THREAD

**Issue by fabbe50** [Toadstool-Studios/Creeper-Overhaul#5]
### Bug Description

Haven't seen the mushroom creeper but rather only the badlands creeper on my mushroom island. 

### How to Reproduce?

1. Install mod
2. Go to mushroom fields biome
3. See badlands creepers instead of mushroom ones.

### Expected Behavior

Seeing mushroom creepers instead of badlands creepers.

### Version

0.2.1

### Mod Loader Version

0.12.12

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
This is fixed I had a typo
