### ISSUE TITLE
[Bug]: Crash with newer builds of Quilt, seems to be looking for classes that no longer exist

### ISSUE THREAD

**Issue by Sunconure11** [Toadstool-Studios/Creeper-Overhaul#51]
### Bug Description

Creeper Overhaul appears to be looking for classes that no longer exist in Quilt. It is possible this error may exist in Fabric too.

### How to Reproduce?

1. Attempt to boot up the game
2. ???
3. Crash

### Expected Behavior

Game to boot up

### Version

Fabric 2.0.3

### Mod Loader Version

1.19.2 - Quilt 0.17.5-Beta 6

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/ujNC058f

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by Sunconure11** [comment]
@ThatGravyBoat I know you said you don't support Quilt last time around, but could you come and check over this issue anyways?

**Comment by SplendidAlakey** [comment]
Will be fixed in the next release: https://github.com/bonsaistudi0s/Creeper-Overhaul/pull/49

**Comment by ThatGravyBoat** [comment]
Fixed in version 2.0.5 when curse approves it.
