### ISSUE TITLE
[Bug]: Creeper overhaul keeps randomly crashing for me

### ISSUE THREAD

**Issue by justawander** [Toadstool-Studios/Creeper-Overhaul#52]
### Bug Description

https://bytebin.lucko.me/oKW4lyt1Ud

### Version

1.3.0

### Mod Loader Version

40.1.84

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by Theisgood** [comment]
I actually just had this exact same crash! LOL yeah I think it has to do with GEKO lib being updated. 

But sadly Ill have to remove for now :( till someone fixes either mods.

**Comment by ThatGravyBoat** [comment]
I will have a version out later to fix this issue but yes its a geckolib issue and I will just have to work around it.

**Comment by ThatGravyBoat** [comment]
Fixed in latest 1.18.2 version
