### ISSUE TITLE
[Feature Request]: Snow Creepers ought to have a loot table

### ISSUE THREAD

**Issue by MuteTiefling** [Toadstool-Studios/Creeper-Overhaul#53]
### Is your feature request related to a problem?

Not sure if a bug, or intended. 

### Solution(s)

Give snow creepers a loot table with at least gun powder and snow.

### Mod Version

2.0.5

### Mod Loader Version

43.1.47

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Added loottable for wool drop from snowy creepers in the latest 1.19 version
