### ISSUE TITLE
[Feature Request]: Config for 1.3.1 that lets users blacklist spawning of specific creepers

### ISSUE THREAD

**Issue by OlliWare** [Toadstool-Studios/Creeper-Overhaul#55]
### Is your feature request related to a problem?

It would be awesome to have a config file for blacklisting the spawning of specific creepers (I'm looking at you bamboo creeper) for 1.3.1 and above. Playing on a 1.18.2 fabric server right now and most players' forests are over-swarmed with bamboo creepers.

### Solution(s)

Make a config file that lets the user blacklist specific creepers

### Describe alternatives you've considered

Make a config file that lets the player input creeperoverhaul:bamboo_creeper and such to prevent it to spawn entirely or from specific biomes. Even better would be if you'd be able to tweak the spawn-rate for each creeper.spawn rate

### Mod Version

1.3.1

### Mod Loader Version

1.18.2 - 0.14.10

### Mod Loader

Fabric

**Comment by markygnlg** [comment]
in the mean time, have you tried the mod "[In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control)" ?

**Comment by OlliWare** [comment]
> in the mean time, have you tried the mod "[In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control)" ?

In Control does not support Fabric, only Forge.

**Comment by markygnlg** [comment]
Oh. I searched google for "minecraft mod mob spawn fabric" & all I found was:
 - [Custom Spawns [Fabric]](https://www.curseforge.com/minecraft/mc-mods/custom-spawns)
 - 
... maybe the option "mobId" = 'Fully-qualified mob Identifier'?

Good luck.

**Comment by markygnlg** [comment]
or maybe edit the jar file yourself (it is a zip file but renamed to jar)

you can rename/remove files with the name of the creeper you don't like & see what happens (then rezip the files & folders, rename the zip to jar, move/copy it into your mods & don't forget to remove the original jar file too)

EDIT: if it's just the skin (the way it looks) that you don't like then you can copy over the png files with other creepers that you do like - but any special characteristics will remain on the original creeper (the one you do not like - ie. it will look different but behave the same)

**Comment by markygnlg** [comment]
WOW!
It was added to v2.0.9!

"Switched to using Resourceful Config
Added config options to disable individual creeper type spawns.

Fixed Mushroom Creepers not exploding when using flint and steel."

Thanks!
