### ISSUE TITLE
[Bug]: No charged creepers

### ISSUE THREAD

**Issue by BlackAures1** [Toadstool-Studios/Creeper-Overhaul#58]
### Bug Description

The texture of the creepers from the mod does not appear that they are charged. 

### How to Reproduce?

/summon creeperoverhaul:jungle_creeper ~ ~ ~ {powered:1}
make boom

### Expected Behavior

I want to visually see that the creeper is charged like in vanilla.

![image](https://user-images.githubusercontent.com/43911230/209443791-063376e6-87b4-4930-903c-b87c917c349d.png)

### Version

creeperoverhaul-1.3.1-forge

### Mod Loader Version

Curseforge Forge 40.1.86 1.18.2

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by BlackAures1** [comment]
May I ask what the reason for rejecting this bug report is? Mods that add charged creepers do not render on your creepers, but have a charge. Summon command do not render this also.

**Comment by ThatGravyBoat** [comment]
I summoned a creeper with the exact command the same version it worked fine so I closed as not reproducible not much else I can do.
