### ISSUE TITLE
[Bug]: Forest creepers afraid of the player

### ISSUE THREAD

**Issue by MarioSMB** [Toadstool-Studios/Creeper-Overhaul#61]
### Bug Description

Not sure if this is intended or a mod conflict, but the "regular" creepers that spawn from normal creeper eggs appear to be afraid of the player. This doesn't occur with the other creeper types.

Here's a picture of the creeper to show which one it is:  
![2023-01-09_02 54 17](https://user-images.githubusercontent.com/1998392/211208941-59c92a9c-ecbe-41ee-8f9d-627484654a1b.png)

### Version

1.3.1

### Mod Loader Version

40.2.0

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
I dont touch the logic of that creeper its purely a reskin of the vanilla creeper with animations and a custom model so that means its likely another mod changing the mechanics of it.

**Comment by MarioSMB** [comment]
Thanks for the heads up, I'll try with a clean install later and report back if it's reproducible.  
Otherwise... I dunno, going through dozens of mods doesn't sound like a fun afternoon!

EDIT: I forgot to mention in the original issue, but this doesn't occur with regular creepers without the mod installed.  
EDIT2: I can't even reproduce this myself anymore, must've been some armor or mod combo that I've since changed. Looking forward to playing with this mod now!

**Comment by ThatGravyBoat** [comment]
That creeper in the screenshot is a reskinned vanilla creeper so that would mean that if the mechanics are weird about it it would be vanilla or another mod as I dont touch the vanilla code.
