### ISSUE TITLE
[Feature Request]: Update to 1.19.3

### ISSUE THREAD

**Issue by ereese99** [Toadstool-Studios/Creeper-Overhaul#62]
### Solution(s)

Is it possible to make this mod compatible with 1.19.3? Thanks

### Mod Version

1.19.3

### Mod Loader Version

N/A

### Mod Loader

Fabric

### Additional context

Just want the mod in 1.19.3

**Comment by ThatGravyBoat** [comment]
1.19.3 will be skipped and we will be porting to 1.19.4 instead
