### ISSUE TITLE
[Bug]: Default creeper animation switched around

### ISSUE THREAD

**Issue by StockiesLad** [Toadstool-Studios/Creeper-Overhaul#67]
### Bug Description

it makes the walking animation when staying still &
the still animation when the creeper is walking.

### How to Reproduce?

Install:
creeperoverhaul-1.18.2-1.3.1-fabric
fabric-api-0.67.0+1.18.2
geckolib-fabric-1.18-3.0.80

### Expected Behavior

For the animations to work properly.

### Version

1.3.1

### Mod Loader Version

1.18.2, 0.14.14

### Mod Loader

Fabric

### Logs or additional context

[latest.log](https://github.com/bonsaistudi0s/Creeper-Overhaul/files/10722376/latest.log)

### Acknowledgement

- [x] I agree that I have read what was said above this check box.

**Comment by BioTechproject27** [comment]
Seems to work fine for most creepers, at least in version 3.0.2. The only exception I found was the bamboo creeper when it's aggrevated, it just slides
