### ISSUE TITLE
[Bug]: Game crash with the mod

### ISSUE THREAD

**Issue by MoustacheKat** [Toadstool-Studios/Creeper-Overhaul#80]
### Bug Description

My game crash everytime i tried to see a creeper, if a chunk load a creeper crash and iuf i try to usea an egg with a creeper crash

### How to Reproduce?

1. Create a world
2. Play
3. Load a chunk with a creeper
4. Crash

### Expected Behavior

See the creeper and continued to play

### Version

1.18.2

### Mod Loader Version

1.18.2-1.3.0-forge

### Mod Loader

Forge

### Logs or additional context

[crash-2023-06-28_17.30.47-client.txt](https://github.com/bonsaistudi0s/Creeper-Overhaul/files/11900172/crash-2023-06-28_17.30.47-client.txt)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
I do not plan on updating 1.18 I suggest using an old version of geckolib that doesnt implement this breaking change
