### ISSUE TITLE
[Feature Request]: Ignite overhauled creepers with flint and steel

### ISSUE THREAD

**Issue by Therkelsen** [Toadstool-Studios/Creeper-Overhaul#81]
### Is your feature request related to a problem?

You can ignite vanilla creepers using flint and steel, you can't do this with overhauled creepers.

### Solution(s)

When you right-click on an overhauled creeper, it should "ignite" it, triggering the explosion sequence.

### Mod Version

3.0.1

### Mod Loader Version

1.20.1 - 0.14.21

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
You can already do this to the creepers that can explode
