### ISSUE TITLE
[Feature Request]: Additional spawning conditions

### ISSUE THREAD

**Issue by Tomatobird8** [Toadstool-Studios/Creeper-Overhaul#85]
### Is your feature request related to a problem?

I'm going to use Bamboo Creepers as a specific example, but this may apply to other creepers from the mod.

The spawing conditions are very lenient, allowing them to spawn in well-lit structures causing built in jungle biomes.

### Solution(s)

Add more spawning conditions to the creeper. For example, allow spawning only when block light is 0 but sunlight can be whatever and/or only spawn on grass type blocks instead of just anything.

### Mod Version

2.0.9

### Mod Loader Version

1.19.2 (0.14.21)

### Mod Loader

Fabric

### Additional context

I experienced this issue in the modpack All of Fabric 6 v1.9.1

**Comment by Rebel459** [comment]
this is present with the snow creeper too, on 1.20. probably affects quite a few of them
