### ISSUE TITLE
[Bug]: Fresh Animations don't work on default creeper

### ISSUE THREAD

**Issue by mpustovoi** [Toadstool-Studios/Creeper-Overhaul#86]
### Bug Description

When the model of a default creeper from the Creeper Overhaul is disabled, the animation from Fresh Animations doesn't work.

### How to Reproduce?

1. Install Fresh Animations and Fabric mods necessary for its operation: Animatica, EMF and ETF.
2. Disable "Replace Default Creeper" option.

### Expected Behavior

Creeper animation should switch to Fresh Animations one when Creeper Overhaul is installed and "Replace Default Creeper" option is disabled.

### Version

3.0.1

### Mod Loader Version

1.20.1 - 0.14.22

### Mod Loader

Fabric

### Logs or additional context

Animatica v0.6
EMF v0.2.13
ETF v4.5.1
Fabric API v0.87.0

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by Psychodeus** [comment]
Was fresh animation works if the creeper overhaul enabled?

**Comment by mpustovoi** [comment]
If Creeper Overhaul animation is enabled, it works as intended (it overrides Fresh Animations).
However, I don't know if it's correct that the creeper doesn't turn its head if the animation from Creeper Overhaul is enabled.

**Comment by millennIumAMbiguity** [comment]
Here I have the same issue on 1.18.2 fabric 
Creeper-Overhaul: 1.3.1
https://i.imgur.com/v3ik9bn.mp4

**Comment by millennIumAMbiguity** [comment]
What is "Replace Default Creeper"? I can't find it.

**Comment by mpustovoi** [comment]
This is one of the mod settings inside the game. 
I guess you need a Mod Menu to see it.

**Comment by mpustovoi** [comment]
Btw, this error was resolved when EMF received the release version.
In this regard, I'm closing the issue.

**Comment by millennIumAMbiguity** [comment]
> This is one of the mod settings inside the game. I guess you need a Mod Menu to see it.
There are no configs.
![image](https://github.com/bonsaistudi0s/Creeper-Overhaul/assets/37588844/2b67ac8b-17a1-482a-88e3-1144a4b6f1bf)

**Comment by millennIumAMbiguity** [comment]
> Btw, this error was resolved when EMF received the release version. In this regard, I'm closing the issue.

I'm using EMF 1.0.2 still have the issue in 1.18.2.

**Comment by mpustovoi** [comment]
> Here I have the same issue on 1.18.2 fabric Creeper-Overhaul: 1.3.1 https://i.imgur.com/v3ik9bn.mp4

When this mod's creeper model is enabled the Fresh Animations one definitely won't work because the mod overrides the creeper's animations besides the texture.
I was wrong about Mod Menu. Creeper Overhaul actually needs **Resourceful Config** mod to edit config directly in the game.
Otherwise, just go to _…/.minecraft/config/creeperoverhaul.jsonc_ and open it with some Notepad and set **replaceDefaultCreeper** to **false**

**Comment by mpustovoi** [comment]
> I'm using EMF 1.0.2 still have the issue in 1.18.2.

I'm playing at 1.20.1. Maybe there are some incompatibilities on older versions. However, with the release version of EMF I just don't know how to fix it then.

**Comment by mpustovoi** [comment]
> There are no configs.

I also just noticed that both Forge and Fabric versions for 1.18.2 don't have Resourceful Config as the required mod.
Then you need to manually edit _…/creeperoverhaul.jsonc_.
