### ISSUE TITLE
[Bug]: No datafixer registration

### ISSUE THREAD

**Issue by GitUser14975** [Toadstool-Studios/Creeper-Overhaul#91]
### Bug Description

This doesn't break anything in the game and everything works fine, but creates unnecessary mess in the game's logs.

`[12:43:32] [Render thread/ERROR]:
 No data fixer registered for jungle_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for bamboo_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for desert_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for badlands_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for hills_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for savannah_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for mushroom_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for swamp_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for dripstone_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for cave_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for dark_oak_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for spruce_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for beach_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for snowy_creeper
[12:43:32] [Render thread/ERROR]:
 No data fixer registered for ocean_creeper`

### How to Reproduce?

Launch the game and you'll find these errors in the log

### Expected Behavior

No errors at all

### Version

3.0.1

### Mod Loader Version

1.20.1 Fabric - 0.14.22

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/1ESZfFri

### Acknowledgement

- [x] I agree that I have read what was said above this check box.

**Comment by Zunwolf1896** [comment]
Can confirm, I am having this as well. 

`<html>
<body>


[21:04:51] [main/ERROR]: No data fixer registered for jungle_creeper
--
222 | [21:04:51] [main/ERROR]: No data fixer registered for bamboo_creeper
223 | [21:04:51] [main/ERROR]: No data fixer registered for desert_creeper
224 | [21:04:51] [main/ERROR]: No data fixer registered for badlands_creeper
225 | [21:04:51] [main/ERROR]: No data fixer registered for hills_creeper
226 | [21:04:51] [main/ERROR]: No data fixer registered for savannah_creeper
227 | [21:04:51] [main/ERROR]: No data fixer registered for mushroom_creeper
228 | [21:04:51] [main/ERROR]: No data fixer registered for swamp_creeper
229 | [21:04:51] [main/ERROR]: No data fixer registered for dripstone_creeper
230 | [21:04:51] [main/ERROR]: No data fixer registered for cave_creeper
231 | [21:04:51] [main/ERROR]: No data fixer registered for dark_oak_creeper
232 | [21:04:51] [main/ERROR]: No data fixer registered for spruce_creeper
233 | [21:04:51] [main/ERROR]: No data fixer registered for beach_creeper
234 | [21:04:51] [main/ERROR]: No data fixer registered for snowy_creeper
235 | [21:04:51] [main/ERROR]: No data fixer registered for ocean_creeper


</body>
</html>`

**Comment by Bowswa** [comment]
This issue should be resolved one of two ways:

[This Link](https://forums.minecraftforge.net/topic/94739-1163-getting-rid-of-data-fixer-error-spam/) is an article talking about how to potentially get around this console error if you dont want to add a datafixer or you have your own setup somewhere.

As someone who has to go through REALLY big log files already, every line of console spam removed helps an absolute ton.

Thank you for your consideration.
