### ISSUE TITLE
[Bug]: Creeper farm not working anywhere

### ISSUE THREAD

**Issue by leftbones** [Toadstool-Studios/Creeper-Overhaul#98]
### Bug Description

We built a creeper farm over a plains biome and creepers will not spawn there no matter what. We initially tried it over an ocean but it wasn't working, so we figured moving it to a plains would help, but nope.

### Version

2.0.9

### Mod Loader Version

43.2.14

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
The mod is to overhaul creepers, we do not make assertions that it will work with vanilla creeper farms.
