### ISSUE TITLE
May I ask if it is possible to add a configuration file so that the material of the original coolie fear will not change, as I would like to install a material pack. The material pack I added and those related to the Creeper have lost their effectiveness

### ISSUE THREAD

**Issue by Mnibr** [Toadstool-Studios/Creeper-Overhaul#99]
### Bug Description

May I ask if it is possible to add a configuration file so that the material of the original coolie fear will not change, as I hope to install a material pack. The material pack and coolie fear related items I added have lost their effectiveness

### How to Reproduce?

May I ask if it is possible to add a configuration file so that the material of the original coolie fear will not change, as I hope to install a material pack. The material pack and coolie fear related items I added have lost their effectiveness

### Expected Behavior

May I ask if it is possible to add a configuration file so that the material of the original coolie fear will not change, as I hope to install a material pack. The material pack and coolie fear related items I added have lost their effectiveness

### Version

1.20.1

### Mod Loader Version

47.1.44

### Mod Loader

Forge

### Logs or additional context

no

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by Mnibr** [comment]
I used translation software, so some words are incorrect. The correct expression should be: May I ask if it is possible to add a configuration file so that the material of the original cool air will not change, as I would like to install a material pack The material pack I added and those related to the Creeper have lost their effectiveness

**Comment by ThatGravyBoat** [comment]
I think you may have the wrong mod, we dont have anything of that nature.
